// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("RdfSharp.DesignTime")>]
[<assembly: AssemblyProductAttribute("RdfSharp")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing RdfSharp.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "RdfSharp.DesignTime"
    let [<Literal>] AssemblyProduct = "RdfSharp"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing RdfSharp."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
