// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Iride.DesignTime")>]
[<assembly: AssemblyProductAttribute("Iride")>]
[<assembly: AssemblyDescriptionAttribute("This library is for the .NET platform implementing Iride.")>]
[<assembly: AssemblyVersionAttribute("1.0.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Iride.DesignTime"
    let [<Literal>] AssemblyProduct = "Iride"
    let [<Literal>] AssemblyDescription = "This library is for the .NET platform implementing Iride."
    let [<Literal>] AssemblyVersion = "1.0.0"
    let [<Literal>] AssemblyFileVersion = "1.0.0"
